# Generated by Django 4.1.5 on 2023-02-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel order', 'can cancel order')]},
        ),
    ]
